# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a630420ef5962d9759a24c6e330c29a4d21af58b3ff2257f0f57514c4c163e2b652e29adbc8937a0ad5c7852131b727afbf81903e3348a8e1342e81f62df4b3

test:
  secret_key_base: f4d0ace0bf7498afc60e327f56744f8c9dfd4411b596a5f68edaa8e2e94457bec4e7d5fb35f5d6af99734dd824a2741c094026954c7d741c5446a2c46b3023eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
